job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}")

    //checkout the code from SCM
    //tsa magie io na tsatoka fa misy documentation
    scm {
        git("https://github.com/manamisoaToussaint/MyFirstMavenProject.git", 'main')
    }

    //Trigers option
    triggers {
        scm('* * * * *')
    }

    //Build
    steps {
        maven('clean package', 'pom.xml')
    }

    //Post Build Actions
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}